name: learn-github-actions
on: [pull_request]
jobs:
  add-code:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Log Submission time
        run: echo "Submitted at " $(date)
      - name: List files
        run: ls -alh
      - name: Run program
        run: find . -name '*.py' | head -n 1 | xargs python3
        shell: bash
